language: node_js
node_js:
  - "8"
before_script:
  - npm install --ignore-scripts

script:
  - npm run postinstall

deploy:
  provider: pages
  local_dir: webapp
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

